//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiichDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Workshop = new HashSet<Workshop>();
        }
    
        public int ID { get; set; }
        public Nullable<int> parentId { get; set; }
        public string label { get; set; }
        public int activate { get; set; }
    
        public virtual ICollection<Workshop> Workshop { get; set; }
    }
}
