//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiichDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public Workshop()
        {
            this.Tag = new HashSet<Tag>();
            this.WatchedBy = new HashSet<User>();
            this.Participants = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Hour { get; set; }
        public int PeopleMin { get; set; }
        public int PeopleMax { get; set; }
        public string Recurence { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Equipement { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Address { get; set; }
        public string Details { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
        public virtual ICollection<User> WatchedBy { get; set; }
        public virtual ICollection<User> Participants { get; set; }
    }
}
